### ISSUE TITLE
The reliability of this method.

### ISSUE THREAD

**Issue by erow** [Linear95/CLUB#9]
I just modified the dimension of samples to 10, and the results were not good for this situation. 
![UV{X NMYBH)_XKA1G2SB3HT](https://user-images.githubusercontent.com/7524356/113871067-19bc2e00-97e5-11eb-9e28-c0004470eb8f.png)
So does CLUB need to tune hyperparameters carefully? 
我需要估计一个1维的c与10维的z之间的互信息，我发现CLUB估计的互信息有很大偏差。请问是CLUB存在一些使用上的限制条件还是对每种情况都需要调整参数？或者估计I(ci;z)的建议。

实验中InfoNCE与CLUB的对比。
![image](https://user-images.githubusercontent.com/7524356/113872908-e8dcf880-97e6-11eb-8a20-b508cd6bc128.png)

**Comment by Linear95** [comment]
Based on the theorem in our paper, the performance of CLUB is based on the quality of the variational approximation q_theta(y|x). Since the dimension of the sample (x,y) is changed, the variational approximation q_\theta(y|x) is supposed to be changed to have a better estimation. My suggestion is to reduce the hidden_size of q_\theta(y|x) for a better approximation to data samples with lower dimensions.

**Comment by LindgeW** [comment]
@erow InfoNCE不是互信息最大化的近似估计吗？为什么和CLUB比较？

**Comment by erow** [comment]
> @erow InfoNCE不是互信息最大化的近似估计吗？为什么和CLUB比较？

目的都是为了估计互信息，只是有的方法是最大化求MI的下界，有的是最小化求MI的上界。
